build_platform:
  linux_aarch64: linux_aarch64
github:
  branch_name: main
  tooling_branch_name: main
conda_build:
  error_overlinking: true
conda_forge_output_validation: true
test_on_native_only: true
provider:
  linux_aarch64: travis
